### ISSUE TITLE
Node telemetry deployment and integration

### ISSUE THREAD

**Issue by DmitriVT** [Atleta-network/atleta-network-deploy#2]
This task involves setting up and integrating telemetry on nodes within a Substrate blockchain network. The goal is to capture and analyze real-time data concerning various network metrics, including block production, transaction processing, and node performance.

**Comment by semeniak97mf** [comment]
https://github.com/Atleta-network/atleta-network-deploy/pull/8

**Comment by semeniak97mf** [comment]
Grafana: http://${DEVNET_HOST}:3000
Polkadot telemetry: http://{DEVNET_HOST}:8081

**Comment by semeniak97mf** [comment]
Grafana: http://${DEVNET_HOST}:3000/
Polkadot telemetry: http://${DEVNET_HOST}:8081/
